In [2]:
import requests

In [ ]:
url='http://127.0.0.1:5003/plot'
requests.post(url,{'playername':'Damian Lillard','date':'4/11/18','cat':'PTS'})

In [18]:
{'playername':'Damian Lillard','date':'4/11/18'}

{'date': '4/11/18', 'playername': 'Damian Lillard'}

In [6]:
usock.close()

In [11]:
from bs4 import BeautifulSoup
import urllib2

url='https://www.basketball-reference.com/players/l/lillada01.html'


fp = urllib2.urlopen(url)
mybytes = fp.read()


soup = BeautifulSoup(mybytes, 'html.parser') 

soup.findAll('p')

AttributeError: ResultSet object has no attribute 'get_text'. You're probably treating a list of items like a single item. Did you call find_all() when you meant to call find()?

In [39]:
line=[x.get_text() for x in soup.findAll('p') if 'Position' in x.get_text()][0]
from collections import OrderedDict


#line= 'Shooting Guard and Small Forward'
pos_dict = OrderedDict()
pos_dict['Point Guard']='PG'
pos_dict['Shooting Guard']='SG'
pos_dict['Small Forward']='SF'
pos_dict['Power Forward']='PF'
pos_dict['Center']='C'


p=''
for pos in pos_dict:
    if pos in line:
        if p=='':
            p=pos_dict[pos]
        else:
            p+=', '+pos_dict[pos]
p            
        

'PG'

In [136]:
import dill
team = 'Portland Trail Blazers'
teampkl_source = 'pkl_obj/' + team.replace(" ", "") + '.dill'
team_obj=dill.load(open(teampkl_source, 'r'))

playerName='Damian Lillard'
pkl_source = 'pkl_obj/'+playerName.replace(" ","") + '.dill'

player_obj = dill.load(open(pkl_source, 'r'))


In [4]:
from IPython.display import display
import pandas as pd
pd.options.display.max_columns = None


In [5]:
team_log=team_obj.game_log['2018']
player_log=player_obj.game_log['2018']

In [29]:
team_log.head()

index Rk  G        Date Home/Away  Opp W/L  Pts OppPts  FG FGA   FG%  3P  \
0      0  1  1  2017-10-18         @  PHO   W  124     76  44  90  .489  14   
1      1  2  2  2017-10-20         @  IND   W  114     96  46  95  .484   9   
2      2  3  3  2017-10-21         @  MIL   L  110    113  34  81  .420  11   
3      3  4  4  2017-10-24       NaN  NOP   W  103     93  33  88  .375  10   
4      4  5  5  2017-10-26       NaN  LAC   L  103    104  35  89  .393  14   

  3PA   3P%  FT FTA   FT% ORB TRB AST STL BLK TOV  PF OppFG OppFGA OppFG%  \
0  24  .583  22  28  .786  15  57  22   8   7  16  20    28     89   .315   
1  19  .474  13  17  .765  11  51  19   5   6   9  26    35     78   .449   
2  28  .393  31  35  .886  13  42  18  10   6  16  22    42     80   .525   
3  29  .345  27  33  .818  18  63  17   7   7  18  22    30     76   .395   
4  31  .452  19  22  .864  16  44  19   5   4   9  26    36     77   .468   

  Opp3P Opp3PA Opp3P% OppFT OppFTA OppFT% OppORB OppTRB OppAST OppSTL OppBLK  \
0     7     27   .259    13     18   .722     10     33     10      9      8   
1     4     18   .222    22     33   .667      6     39     15      1      4   
2     7     18   .389    22     30   .733      7     35     22      9      8   
3     9     30   .300    24     32   .750      4     42     17      5      7   
4     9     28   .321    23     36   .639     14     46     11      4      5   

  OppTOV OppPF  Away  daysRest  
0     16    22     1      99.0  
1     12    17     1       2.0  
2     14    23     1       1.0  
3     17    26     0       3.0  
4     11    19     0       2.0

In [5]:
team_log

index  Rk   G        Date Home/Away  Opp W/L  Pts OppPts  FG  FGA   FG%  \
0       0   1   1  2017-10-18         @  PHO   W  124     76  44   90  .489   
1       1   2   2  2017-10-20         @  IND   W  114     96  46   95  .484   
2       2   3   3  2017-10-21         @  MIL   L  110    113  34   81  .420   
3       3   4   4  2017-10-24       NaN  NOP   W  103     93  33   88  .375   
4       4   5   5  2017-10-26       NaN  LAC   L  103    104  35   89  .393   
5       5   6   6  2017-10-28       NaN  PHO   W  114    107  40   91  .440   
6       6   7   7  2017-10-30       NaN  TOR   L   85     99  31   80  .388   
7       7   8   8  2017-11-01         @  UTA   L  103    112  37   93  .398   
8       8   9   9  2017-11-02       NaN  LAL   W  113    110  40   86  .465   
9       9  10  10  2017-11-05       NaN  OKC   W  103     99  37   74  .500   
10     10  11  11  2017-11-07       NaN  MEM   L   97     98  36   81  .444   
11     11  12  12  2017-11-10       NaN  BRK   L   97    101  40   95  .421   
12     12  13  13  2017-11-13       NaN  DEN   W   99     82  38   73  .521   
13     13  14  14  2017-11-15       NaN  ORL   W   99     94  38   87  .437   
14     14  15  15  2017-11-17         @  SAC   L   82     86  30   81  .370   
15     15  16  16  2017-11-18       NaN  SAC   W  102     90  38   70  .543   
16     16  17  17  2017-11-20         @  MEM   W  100     92  33   83  .398   
17     17  18  18  2017-11-22         @  PHI   L   81    101  30   89  .337   
18     18  19  19  2017-11-24         @  BRK   W  127    125  48   96  .500   
19     19  20  20  2017-11-25         @  WAS   W  108    105  41   80  .513   
20     22  21  21  2017-11-27         @  NYK   W  103     91  37   83  .446   
21     23  22  22  2017-11-30       NaN  MIL   L   91    103  35   83  .422   
22     24  23  23  2017-12-02       NaN  NOP   L  116    123  47  105  .448   
23     25  24  24  2017-12-05       NaN  WAS   L   92    106  32   78  .410   
24     26  25  25  2017-12-09       NaN  HOU   L  117    124  45   88  .511   
25     27  26  26  2017-12-11         @  GSW   L  104    111  37   88  .420   
26     28  27  27  2017-12-13         @  MIA   W  102     95  36   72  .500   
27     29  28  28  2017-12-15         @  ORL   W   95     88  37   86  .430   
28     30  29  29  2017-12-16         @  CHO   W   93     91  37   79  .468   
29     31  30  30  2017-12-18         @  MIN   L  107    108  46   84  .548   
..    ...  ..  ..         ...       ...  ...  ..  ...    ...  ..  ...   ...   
52     56  53  53  2018-02-04         @  BOS   L   96     97  36   91  .396   
53     57  54  54  2018-02-05         @  DET   L   91    111  37   94  .394   
54     58  55  55  2018-02-08       NaN  CHO   W  109    103  41   90  .456   
55     59  56  56  2018-02-09         @  SAC   W  118    100  43   88  .489   
56     60  57  57  2018-02-11       NaN  UTA   L   96    115  33   81  .407   
57     61  58  58  2018-02-14       NaN  GSW   W  123    117  45   93  .484   
58     62  59  59  2018-02-23         @  UTA   W  100     81  39   87  .448   
59     63  60  60  2018-02-24         @  PHO   W  106    104  39   99  .394   
60     66  61  61  2018-02-27       NaN  SAC   W  116     99  44   84  .524   
61     67  62  62  2018-03-01       NaN  MIN   W  108     99  36   92  .391   
62     68  63  63  2018-03-03       NaN  OKC   W  108    100  39   88  .443   
63     69  64  64  2018-03-05         @  LAL   W  108    103  35   83  .422   
64     70  65  65  2018-03-06       NaN  NYK   W  111     87  35   81  .432   
65     71  66  66  2018-03-09       NaN  GSW   W  125    108  44   89  .494   
66     72  67  67  2018-03-12       NaN  MIA   W  115     99  38   83  .458   
67     73  68  68  2018-03-15       NaN  CLE   W  113    105  43   96  .448   
68     74  69  69  2018-03-17       NaN  DET   W  100     87  38   87  .437   
69     75  70  70  2018-03-18         @  LAC   W  122    109  46   92  .500   
70     76  71  71  2018-03-20       NaN  HOU   L  111 

In [25]:

#player_log['Rk']=player_log['Rk'].astype('float')
#team_log['Rk']=team_log['Rk'].astype('float')

team_log=team_log.rename(columns={'Pts':'PTS'})
cols = ['Rk','PTS','FG','FGA','3P','3PA','FT','FTA','TRB','AST','STL','BLK','TOV']
new_player_log=pd.merge(player_log, team_log[cols], on=['Rk'], how='left')
new_player_log

index    Rk   G        Date     Age   Tm Unnamed: 5  Opp Unnamed: 7  GS  \
0       0   1.0   1  2017-10-18  27-095  POR          @  PHO    W (+48)   1   
1       1   2.0   2  2017-10-20  27-097  POR          @  IND    W (+18)   1   
2       2   3.0   3  2017-10-21  27-098  POR          @  MIL     L (-3)   1   
3       3   4.0   4  2017-10-24  27-101  POR        NaN  NOP    W (+10)   1   
4       4   5.0   5  2017-10-26  27-103  POR        NaN  LAC     L (-1)   1   
5       5   6.0   6  2017-10-28  27-105  POR        NaN  PHO     W (+7)   1   
6       6   7.0   7  2017-10-30  27-107  POR        NaN  TOR    L (-14)   1   
7       7   8.0   8  2017-11-01  27-109  POR          @  UTA     L (-9)   1   
8       8   9.0   9  2017-11-02  27-110  POR        NaN  LAL     W (+3)   1   
9       9  10.0  10  2017-11-05  27-113  POR        NaN  OKC     W (+4)   1   
10     10  11.0  11  2017-11-07  27-115  POR        NaN  MEM     L (-1)   1   
11     11  12.0  12  2017-11-10  27-118  POR        NaN  BRK     L (-4)   1   
12     12  13.0  13  2017-11-13  27-121  POR        NaN  DEN    W (+17)   1   
13     13  14.0  14  2017-11-15  27-123  POR        NaN  ORL     W (+5)   1   
14     14  15.0  15  2017-11-17  27-125  POR          @  SAC     L (-4)   1   
15     15  16.0  16  2017-11-18  27-126  POR        NaN  SAC    W (+12)   1   
16     16  17.0  17  2017-11-20  27-128  POR          @  MEM     W (+8)   1   
17     17  18.0  18  2017-11-22  27-130  POR          @  PHI    L (-20)   1   
18     18  19.0  19  2017-11-24  27-132  POR          @  BRK     W (+2)   1   
19     19  20.0  20  2017-11-25  27-133  POR          @  WAS     W (+3)   1   
20     21  21.0  21  2017-11-27  27-135  POR          @  NYK    W (+12)   1   
21     22  22.0  22  2017-11-30  27-138  POR        NaN  MIL    L (-12)   1   
22     23  23.0  23  2017-12-02  27-140  POR        NaN  NOP     L (-7)   1   
23     24  24.0  24  2017-12-05  27-143  POR        NaN  WAS    L (-14)   1   
24     25  25.0  25  2017-12-09  27-147  POR        NaN  HOU     L (-7)   1   
25     26  26.0  26  2017-12-11  27-149  POR          @  GSW     L (-7)   1   
26     27  27.0  27  2017-12-13  27-151  POR          @  MIA     W (+7)   1   
27     28  28.0  28  2017-12-15  27-153  POR          @  ORL     W (+7)   1   
28     29  29.0  29  2017-12-16  27-154  POR          @  CHO     W (+2)   1   
29     30  30.0  30  2017-12-18  27-156  POR          @  MIN     L (-1)   1   
..    ...   ...  ..         ...     ...  ...        ...  ...        ...  ..   
43     52  51.0  44  2018-01-31  27-200  POR        NaN  CHI    W (+16)   1   
44     53  52.0  45  2018-02-02  27-202  POR          @  TOR    L (-25)   1   
45     54  53.0  46  2018-02-04  27-204  POR          @  BOS     L (-1)   1   
46     55  54.0  47  2018-02-05  27-205  POR          @  DET    L (-20)   1   
47     56  55.0  48  2018-02-08  27-208  POR        NaN  CHO     W (+6)   1   
48     57  56.0  49  2018-02-09  27-209  POR          @  SAC    W (+18)   1   
49     58  57.0  50  2018-02-11  27-211  POR        NaN  UTA    L (-19)   1   
50     59  58.0  51  2018-02-14  27-214  POR        NaN  GSW     W (+6)   1   
51     60  59.0  52  2018-02-23  27-223  POR          @  UTA    W (+19)   1   
52     61  60.0  53  2018-02-24  27-224  POR          @  PHO     W (+2)   1   
53     63  61.0  54  2018-02-27  27-227  POR        NaN  SAC    W (+17)   1   
54     64  62.0  55  2018-03-01  27-229  POR        NaN  MIN     W (+9)   1   
55     65  63.0  56  2018-03-03  27-231  POR        NaN  OKC     W (+8)   1   
56     66  64.0  57  2018-03-05  27-233  POR          @  LAL     W (+5)   1   
57     67  65.0  58  2018-03-06  27-234  POR        NaN  NYK    W (+24)   1   
58     68  66.0  59  2018-03-09  27-237  POR        NaN  GSW    W (+17)   1   
59     69  67.0  60  2018-03-12  27-240  POR        NaN  MIA    W (+16)   1   
60     70  68.0  61  2018-03-15  27-243  POR        NaN  CLE     W (+8)   1   
61     71  69.0  62  2018-03-17  27-245  POR        Na

In [28]:
cats = ['Pts','FG','FGA','3P','3PA','FT','FTA','TRB','AST','STL','BLK','TOV']
player_log.map(lambda x: team_log[cat] for cat in cats)    

index  Rk  G        Date     Age   Tm Unnamed: 5  Opp Unnamed: 7  GS  \
0      0   1  1  2017-10-18  27-095  POR          @  PHO    W (+48)   1   
1      1   2  2  2017-10-20  27-097  POR          @  IND    W (+18)   1   
2      2   3  3  2017-10-21  27-098  POR          @  MIL     L (-3)   1   
3      3   4  4  2017-10-24  27-101  POR        NaN  NOP    W (+10)   1   
4      4   5  5  2017-10-26  27-103  POR        NaN  LAC     L (-1)   1   

      MP  FG  FGA    FG%  3P  3PA    3P%  FT  FTA    FT%  ORB  DRB  TRB  AST  \
0  29:39  10   20  0.500   4    6  0.667   3    3  1.000    3    2    5    5   
1  32:59   7   17  0.412   0    3  0.000   4    4  1.000    0    7    7    7   
2  34:27   6   15  0.400   3    6  0.500  11   12  0.917    2    3    5    4   
3  35:19   3   16  0.188   1    8  0.125   6    9  0.667    1    4    5    7   
4  38:20   7   19  0.368   4    9  0.444   7    7  1.000    0    2    2    6   

   STL  BLK  TOV  PF  PTS  GmSc  +/-  Away  daysRest  index_team Rk_team  \
0    1    3    0   1   27  25.9   34     1      99.0         1.0       2   
1    1    1    0   2   18  16.8   25     1       2.0         2.0       3   
2    4    0    6   5   26  18.6   -5     1       1.0         3.0       4   
3    1    0    6   0   13   3.6    3     0       3.0         4.0       5   
4    0    0    1   3   25  17.1    1     0       2.0         5.0       6   

  G_team   Date_team Home/Away Opp_team W/L  Pts OppPts FG_team FGA_team  \
0      2  2017-10-20         @      IND   W  114     96      46       95   
1      3  2017-10-21         @      MIL   L  110    113      34       81   
2      4  2017-10-24       NaN      NOP   W  103     93      33       88   
3      5  2017-10-26       NaN      LAC   L  103    104      35       89   
4      6  2017-10-28       NaN      PHO   W  114    107      40       91   

  FG%_team 3P_team 3PA_team 3P%_team FT_team FTA_team FT%_team ORB_team  \
0     .484       9       19     .474      13       17     .765       11   
1     .420      11       28     .393      31       35     .886       13   
2     .375      10       29     .345      27       33     .818       18   
3     .393      14       31     .452      19       22     .864       16   
4     .440      11       26     .423      23       28     .821       12   

  TRB_team AST_team STL_team BLK_team TOV_team PF_team OppFG OppFGA OppFG%  \
0       51       19        5        6        9      26    35     78   .449   
1       42       18       10        6       16      22    42     80   .525   
2       63       17        7        7       18      22    30     76   .395   
3       44       19        5        4        9      26    36     77   .468   
4       53       27        8        7       14      26    37     87   .425   

  Opp3P Opp3PA Opp3P% OppFT OppFTA OppFT% OppORB OppTRB OppAST OppSTL OppBLK  \
0     4     18   .222    22     33   .667      6     39     15      1      4   
1     7     18   .389    22     30   .733      7     35     22      9      8   
2     9     30   .300    24     32   .750      4     42     17      5      7   
3     9     28   .321    23     36   .639     14     46     11      4      5   
4     9     26   .346    24     30   .800     12     46     21     12      7   

  OppTOV OppPF  Away_team  daysRest_team  
0     12    17        1.0            2.0  
1     14    23        1.0            1.0  
2     17    26        0.0            3.0  
3     11    19        0.0            2.0  
4     17    23        0.0            2.0

In [30]:
new_player_log.columns=[col.replace('_x','') if '_x' in col else col for col in new_player_log.columns ]
new_player_log

index    Rk   G        Date     Age   Tm Unnamed: 5  Opp Unnamed: 7  GS  \
0       0   1.0   1  2017-10-18  27-095  POR          @  PHO    W (+48)   1   
1       1   2.0   2  2017-10-20  27-097  POR          @  IND    W (+18)   1   
2       2   3.0   3  2017-10-21  27-098  POR          @  MIL     L (-3)   1   
3       3   4.0   4  2017-10-24  27-101  POR        NaN  NOP    W (+10)   1   
4       4   5.0   5  2017-10-26  27-103  POR        NaN  LAC     L (-1)   1   
5       5   6.0   6  2017-10-28  27-105  POR        NaN  PHO     W (+7)   1   
6       6   7.0   7  2017-10-30  27-107  POR        NaN  TOR    L (-14)   1   
7       7   8.0   8  2017-11-01  27-109  POR          @  UTA     L (-9)   1   
8       8   9.0   9  2017-11-02  27-110  POR        NaN  LAL     W (+3)   1   
9       9  10.0  10  2017-11-05  27-113  POR        NaN  OKC     W (+4)   1   
10     10  11.0  11  2017-11-07  27-115  POR        NaN  MEM     L (-1)   1   
11     11  12.0  12  2017-11-10  27-118  POR        NaN  BRK     L (-4)   1   
12     12  13.0  13  2017-11-13  27-121  POR        NaN  DEN    W (+17)   1   
13     13  14.0  14  2017-11-15  27-123  POR        NaN  ORL     W (+5)   1   
14     14  15.0  15  2017-11-17  27-125  POR          @  SAC     L (-4)   1   
15     15  16.0  16  2017-11-18  27-126  POR        NaN  SAC    W (+12)   1   
16     16  17.0  17  2017-11-20  27-128  POR          @  MEM     W (+8)   1   
17     17  18.0  18  2017-11-22  27-130  POR          @  PHI    L (-20)   1   
18     18  19.0  19  2017-11-24  27-132  POR          @  BRK     W (+2)   1   
19     19  20.0  20  2017-11-25  27-133  POR          @  WAS     W (+3)   1   
20     21  21.0  21  2017-11-27  27-135  POR          @  NYK    W (+12)   1   
21     22  22.0  22  2017-11-30  27-138  POR        NaN  MIL    L (-12)   1   
22     23  23.0  23  2017-12-02  27-140  POR        NaN  NOP     L (-7)   1   
23     24  24.0  24  2017-12-05  27-143  POR        NaN  WAS    L (-14)   1   
24     25  25.0  25  2017-12-09  27-147  POR        NaN  HOU     L (-7)   1   
25     26  26.0  26  2017-12-11  27-149  POR          @  GSW     L (-7)   1   
26     27  27.0  27  2017-12-13  27-151  POR          @  MIA     W (+7)   1   
27     28  28.0  28  2017-12-15  27-153  POR          @  ORL     W (+7)   1   
28     29  29.0  29  2017-12-16  27-154  POR          @  CHO     W (+2)   1   
29     30  30.0  30  2017-12-18  27-156  POR          @  MIN     L (-1)   1   
..    ...   ...  ..         ...     ...  ...        ...  ...        ...  ..   
43     52  51.0  44  2018-01-31  27-200  POR        NaN  CHI    W (+16)   1   
44     53  52.0  45  2018-02-02  27-202  POR          @  TOR    L (-25)   1   
45     54  53.0  46  2018-02-04  27-204  POR          @  BOS     L (-1)   1   
46     55  54.0  47  2018-02-05  27-205  POR          @  DET    L (-20)   1   
47     56  55.0  48  2018-02-08  27-208  POR        NaN  CHO     W (+6)   1   
48     57  56.0  49  2018-02-09  27-209  POR          @  SAC    W (+18)   1   
49     58  57.0  50  2018-02-11  27-211  POR        NaN  UTA    L (-19)   1   
50     59  58.0  51  2018-02-14  27-214  POR        NaN  GSW     W (+6)   1   
51     60  59.0  52  2018-02-23  27-223  POR          @  UTA    W (+19)   1   
52     61  60.0  53  2018-02-24  27-224  POR          @  PHO     W (+2)   1   
53     63  61.0  54  2018-02-27  27-227  POR        NaN  SAC    W (+17)   1   
54     64  62.0  55  2018-03-01  27-229  POR        NaN  MIN     W (+9)   1   
55     65  63.0  56  2018-03-03  27-231  POR        NaN  OKC     W (+8)   1   
56     66  64.0  57  2018-03-05  27-233  POR          @  LAL     W (+5)   1   
57     67  65.0  58  2018-03-06  27-234  POR        NaN  NYK    W (+24)   1   
58     68  66.0  59  2018-03-09  27-237  POR        NaN  GSW    W (+17)   1   
59     69  67.0  60  2018-03-12  27-240  POR        NaN  MIA    W (+16)   1   
60     70  68.0  61  2018-03-15  27-243  POR        NaN  CLE     W (+8)   1   
61     71  69.0  62  2018-03-17  27-245  POR        Na

In [134]:
from sklearn.dummy import DummyRegressor
def addRegressionModels(data):
    cats= ['FG','FGA','3P','3PA','FT','FTA','TRB','AST','STL','BLK','TOV','PTS']
    features=['G','Away','daysRest']
    
    # Regression Models
    models=dict()
    models['dummyReg']=dict()
    models['RFG']=dict()
    for cat in cats:
        # add opponent rating per category
        temp_features=[]
        temp_features+=features
        temp_features.append(cat+'_y')

        # convert to numeric objects
        X=data[temp_features].apply(pd.to_numeric)
        yi=data[cat].apply(pd.to_numeric)
        print X, yi


        ## Dummy Regressor to return season averages regardless of predictions
        dummyreg=DummyRegressor(strategy='mean')
        dummyreg.fit(X,yi)
        models['dummyReg'][cat]=dummyreg

In [135]:
addRegressionModels(player_log)

     G  Away  daysRest  FG_y
0    1     1      99.0    44
1    2     1       2.0    46
2    3     1       1.0    34
3    4     0       3.0    33
4    5     0       2.0    35
5    6     0       2.0    40
6    7     0       2.0    31
7    8     1       2.0    37
8    9     0       1.0    40
9   10     0       3.0    37
10  11     0       2.0    36
11  12     0       3.0    40
12  13     0       3.0    38
13  14     0       2.0    38
14  15     1       2.0    30
15  16     0       1.0    38
16  17     1       2.0    33
17  18     1       2.0    30
18  19     1       2.0    48
19  20     1       1.0    41
20  21     1       2.0    37
21  22     0       3.0    35
22  23     0       2.0    47
23  24     0       3.0    32
24  25     0       4.0    45
25  26     1       2.0    37
26  27     1       2.0    36
27  28     1       2.0    37
28  29     1       1.0    37
29  30     1       2.0    46
..  ..   ...       ...   ...
43  44     0       1.0    46
44  45     1       2.0    37
45  46     1  

[73 rows x 4 columns] 0      6
1      3
2      6
3      8
4      9
5      8
6      8
7     15
8      6
9      5
10     5
11     5
12     8
13    10
14    14
15     7
16     4
17    13
18     6
19     8
20     6
21     7
22    11
23     9
24    16
25    13
26     6
27     6
28     9
29     7
      ..
43     5
44     7
45     9
46     5
47    11
48    13
49     8
50    11
51     7
52    11
53     8
54    12
55     8
56    11
57    11
58    10
59    14
60     8
61    10
62     6
63     7
64    11
65     7
66     9
67    10
68     8
69    10
70    12
71    10
72    10
Name: 3PA, dtype: int64
     G  Away  daysRest  FT_y
0    1     1      99.0    22
1    2     1       2.0    13
2    3     1       1.0    31
3    4     0       3.0    27
4    5     0       2.0    19
5    6     0       2.0    23
6    7     0       2.0    15
7    8     1       2.0    20
8    9     0       1.0    24
9   10     0       3.0    22
10  11     0       2.0    19
11  12     0       3.0     9
12  13     0       3.0    16

Name: AST, dtype: int64
     G  Away  daysRest  STL_y
0    1     1      99.0      8
1    2     1       2.0      5
2    3     1       1.0     10
3    4     0       3.0      7
4    5     0       2.0      5
5    6     0       2.0      8
6    7     0       2.0      5
7    8     1       2.0      8
8    9     0       1.0      7
9   10     0       3.0      6
10  11     0       2.0      9
11  12     0       3.0      4
12  13     0       3.0     12
13  14     0       2.0      7
14  15     1       2.0      8
15  16     0       1.0      6
16  17     1       2.0      1
17  18     1       2.0      8
18  19     1       2.0      5
19  20     1       1.0      3
20  21     1       2.0     10
21  22     0       3.0      5
22  23     0       2.0      6
23  24     0       3.0      2
24  25     0       4.0      4
25  26     1       2.0     11
26  27     1       2.0      7
27  28     1       2.0      7
28  29     1       1.0      2
29  30     1       2.0      6
..  ..   ...       ...    ...
43  44     0    

In [110]:
import datetime as dt
import numpy as np
features = ['G', #game number
			'daysRest',
			'Away', #1=away, 0=home
			#'oppdaysRest','oppAway',
			#'oppRating',
			#'injTeammates',
			#'injOpp'
			]

cats = [u'FG', u'FGA',  u'3P',
       u'3PA',  u'FT', u'FTA', u'TRB', u'AST',
       u'STL', u'BLK', u'TOV', u'PTS']



def get_teamdata(teamName):
    pkl_source = 'pkl_obj/' + teamName.replace(" ", "") + '.dill'
    a = dill.load(open(pkl_source, 'r'))
    return a

def analyzer(obj, date, opp_obj, season='2018'):
    data=obj.game_log[season]
    inputdate_datetime=dt.datetime.strptime(date,'%m/%d/%y')
    formatted_date=dt.datetime.strptime(date, '%m/%d/%y').strftime('%Y-%m-%d')

    feature_inputs = data[features][data['Date']==formatted_date].astype('float').values #  e.g. days rest, game number, home/away
    cols=['Season Average','Predictions']

    # If input data occurred in past, include results
    results=pd.DataFrame(index=cats, columns=cols)
    if inputdate_datetime<dt.datetime.now():
        actual_results=data[cats][data['Date']==formatted_date].squeeze() 
        results['Actual'] = actual_results.astype('float')
    
    # Get opponent average data, categories allowed / given up / caused
    opp_gamelog=opp_obj.game_log['2018'].rename(columns={'OppPts':'OppPTS'})
    opp_avg=[opp_gamelog['Opp'+cat].astype('float').mean() for cat in cats]

    
    # Call regressor models
    dummyReg=obj.models['2018']['dummyReg']
    RFG=obj.models['2018']['RFG']
    
    # Get predictions from models based on feature input, including oppponent rating for each category
    for i, cat in enumerate(cats):
        temp_feature_inputs=feature_inputs
        
        temp_feature_inputs=np.append(temp_feature_inputs,opp_avg[i])
        print temp_feature_inputs
        results.loc[cat,'Season Average']= dummyReg[cat].predict(temp_feature_inputs)[0]
        results.loc[cat,'Predictions']= RFG[cat].predict(temp_feature_inputs)[0]
    print results

In [140]:
player_obj.models['2018']['RFG']['PTS'].feature_importances_

array([ 0.50233466,  0.06919707,  0.04795108,  0.38051719])

In [137]:

analyzer(player_obj, '4/11/18', get_teamdata('Utah Jazz'))

[ 73.          2.          0.         37.2804878]
[ 73.           2.           0.          82.97560976]
[ 73.           2.           0.           9.48780488]
[ 73.           2.           0.          25.98780488]

/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a si


[ 73.           2.           0.          15.79268293]
[ 73.           2.           0.          20.48780488]
[ 73.          2.          0.         41.6097561]
[ 73.           2.           0.          19.95121951]

/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a si


[ 73.           2.           0.           8.26829268]
[ 73.           2.           0.           4.63414634]
[ 73.           2.           0.          14.47560976]

/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a si


[ 73.           2.           0.          99.84146341]
    Season Average Predictions  Actual
FG         8.50685     9.00698    13.0
FGA        19.3836     19.4311    25.0
3P         3.10959     3.03638     4.0
3PA        8.61644     8.33004    10.0
FT         6.75342     9.11378     6.0
FTA        7.36986     9.14916     6.0
TRB        4.45205      4.2245     1.0
AST        6.58904     7.12957    10.0
STL        1.05479     1.38791     1.0
BLK       0.369863    0.259677     0.0
TOV        2.82192     3.70253     0.0
PTS        26.8767     26.0513    36.0


/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a si

In [121]:
player_log[player_log['Date']==dt.datetime.strptime('4/11/18', '%m/%d/%y') ]

Empty DataFrame
Columns: [index, Rk, G, Date, Age, Tm, Unnamed: 5, Opp, Unnamed: 7, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, GmSc, +/-, Away, daysRest, PTS_y, FG_y, FGA_y, 3P_y, 3PA_y, FT_y, FTA_y, TRB_y, AST_y, STL_y, BLK_y, TOV_y]
Index: []

In [129]:
player_log['Date'] =  pd.to_datetime(player_log['Date'])
player_log[player_log['Date']==dt.datetime.strptime('4/11/18', '%m/%d/%y') ]['Opp'].values[0]

'UTA'

In [124]:
[dt.datetime.strptime(date, '%Y-%m-%d') for date in player_log['Date']] 

[datetime.datetime(2017, 10, 18, 0, 0),
 datetime.datetime(2017, 10, 20, 0, 0),
 datetime.datetime(2017, 10, 21, 0, 0),
 datetime.datetime(2017, 10, 24, 0, 0),
 datetime.datetime(2017, 10, 26, 0, 0),
 datetime.datetime(2017, 10, 28, 0, 0),
 datetime.datetime(2017, 10, 30, 0, 0),
 datetime.datetime(2017, 11, 1, 0, 0),
 datetime.datetime(2017, 11, 2, 0, 0),
 datetime.datetime(2017, 11, 5, 0, 0),
 datetime.datetime(2017, 11, 7, 0, 0),
 datetime.datetime(2017, 11, 10, 0, 0),
 datetime.datetime(2017, 11, 13, 0, 0),
 datetime.datetime(2017, 11, 15, 0, 0),
 datetime.datetime(2017, 11, 17, 0, 0),
 datetime.datetime(2017, 11, 18, 0, 0),
 datetime.datetime(2017, 11, 20, 0, 0),
 datetime.datetime(2017, 11, 22, 0, 0),
 datetime.datetime(2017, 11, 24, 0, 0),
 datetime.datetime(2017, 11, 25, 0, 0),
 datetime.datetime(2017, 11, 27, 0, 0),
 datetime.datetime(2017, 11, 30, 0, 0),
 datetime.datetime(2017, 12, 2, 0, 0),
 datetime.datetime(2017, 12, 5, 0, 0),
 datetime.datetime(2017, 12, 9, 0, 0),
 dateti