# If not already built, create player object containing scraped game log data and regression models. 

If 'new', scrape for bball-ref.com to get up to date game logs, apply features, build regressor models, and then serialize with dill. If not new, load dill object. 

In [1]:
import dill
import nba_stats
playerName='Damian Lillard'
new=False
pkl_source = 'pkl_obj/'+playerName.replace(" ","") + '.dill'
if new==True:
    obj = nba_stats.player_scraper(playerName)
    dill.dump(obj, open(pkl_source, 'w'))
else:
    obj = dill.load(open(pkl_source, 'r'))

# Load Player Data

In [ ]:
import bball_app

obj=bball_app.get_data(playerName)
data=obj.game_log['2018']

In [1]:
import bball_app
date='4/11/18'
playerName='Damian Lillard'
obj=bball_app.get_data(playerName)
#results=bball_app.analyzer(obj,date)


/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.19.1 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.19.1 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator RandomForestRegressor from version 0.19.1 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [30]:
import pandas as pd
import datetime as dt
df=obj.game_log['2018']

formatted_date=dt.datetime.strptime('4/11/18', '%m/%d/%y').strftime('%Y-%m-%d')

print formatted_date in df['Date'].values


True


In [34]:
date_text='4343'
try:
    dt.datetime.strptime(date_text, '%Y-%m-%d')
except ValueError:
    raise ValueError("Incorrect data format, should be YYYY-MM-DD")


ValueError: Incorrect data format, should be YYYY-MM-DD

In [ ]:
import nba_stats
teamURLdict = nba_stats.getTeamURLdict()

In [4]:
for team in teamURLdict:
    print team

Los Angeles Lakers
Chicago Bulls
Philadelphia 76ers
San Antonio Spurs
Houston Rockets
Detroit Pistons
Boston Celtics
Miami Heat
Orlando Magic
Portland Trail Blazers
Golden State Warriors
New York Knicks
Washington Wizards
Dallas Mavericks
Minnesota Timberwolves
Los Angeles Clippers
Oklahoma City Thunder
Charlotte Hornets
Milwaukee Bucks
Memphis Grizzlies
Toronto Raptors
Utah Jazz
Phoenix Suns
Sacramento Kings
New Orleans Pelicans
Cleveland Cavaliers
Atlanta Hawks
Brooklyn Nets
Indiana Pacers
Denver Nuggets


In [12]:
import nba_stats
import dill
for team in teamURLdict:
    if team not in ['Charlotte Hornets','New Orleans Pelicans','Brooklyn Nets']:
        print team
        teampkl_source = 'pkl_obj/' + team.replace(" ", "") + '.dill'
        obj = nba_stats.teamScraper(team)
        dill.dump(obj, open(teampkl_source, 'w'))

Los Angeles Lakers
Chicago Bulls
Philadelphia 76ers
San Antonio Spurs
Houston Rockets
Detroit Pistons
Boston Celtics
Miami Heat
Orlando Magic
Portland Trail Blazers
Golden State Warriors
New York Knicks
Washington Wizards
Dallas Mavericks
Minnesota Timberwolves
Los Angeles Clippers
Oklahoma City Thunder
Milwaukee Bucks
Memphis Grizzlies
Toronto Raptors
Utah Jazz
Phoenix Suns
Sacramento Kings
Cleveland Cavaliers
Atlanta Hawks
Indiana Pacers
Denver Nuggets


In [30]:
new=False
team = 'Los Angeles Lakers'
teampkl_source = 'pkl_obj/' + team.replace(" ", "") + '.dill'
if new==True:
    obj = team_scraper(team)
    dill.dump(obj, open(teampkl_source, 'w'))
else:
    obj = dill.load(open(teampkl_source, 'r'))

In [31]:
obj.game_log['2018']

index  Rk   G        Date Home/Away  Opp W/L  Pts OppPts  FG   ...     \
0       0   1   1  2017-10-19       NaN  LAC   L   92    108  37   ...      
1       1   2   2  2017-10-20         @  PHO   W  132    130  48   ...      
2       2   3   3  2017-10-22       NaN  NOP   L  112    119  44   ...      
3       3   4   4  2017-10-25       NaN  WAS   W  102     99  41   ...      
4       4   5   5  2017-10-27       NaN  TOR   L   92    101  36   ...      
5       5   6   6  2017-10-28         @  UTA   L   81     96  31   ...      
6       6   7   7  2017-10-31       NaN  DET   W  113     93  45   ...      
7       7   8   8  2017-11-02         @  POR   L  110    113  43   ...      
8       8   9   9  2017-11-03       NaN  BRK   W  124    112  48   ...      
9       9  10  10  2017-11-05       NaN  MEM   W  107    102  40   ...      
10     10  11  11  2017-11-08         @  BOS   L   96    107  37   ...      
11     11  12  12  2017-11-09         @  WAS   L   95    111  31   ...      
12     12  13  13  2017-11-11         @  MIL   L   90     98  31   ...      
13     13  14  14  2017-11-13         @  PHO   W  100     93  39   ...      
14     14  15  15  2017-11-15       NaN  PHI   L  109    115  42   ...      
15     15  16  16  2017-11-17       NaN  PHO   L  113    122  45   ...      
16     16  17  17  2017-11-19       NaN  DEN   W  127    109  53   ...      
17     17  18  18  2017-11-21       NaN  CHI   W  103     94  36   ...      
18     18  19  19  2017-11-22         @  SAC   L  102    113  39   ...      
19     19  20  20  2017-11-27         @  LAC   L  115    120  44   ...      
20     22  21  21  2017-11-29       NaN  GSW   L  123    127  47   ...      
21     23  22  22  2017-12-02         @  DEN   L  100    115  38   ...      
22     24  23  23  2017-12-03       NaN  HOU   L   95    118  32   ...      
23     25  24  24  2017-12-07         @  PHI   W  107    104  42   ...      
24     26  25  25  2017-12-09         @  CHO   W  110     99  43   ...      
25     27  26  26  2017-12-12         @  NYK   L  109    113  42   ...      
26     28  27  27  2017-12-14         @  CLE   L  112    121  47   ...      
27     29  28  28  2017-12-18       NaN  GSW   L  114    116  41   ...      
28     30  29  29  2017-12-20         @  HOU   W  122    116  40   ...      
29     31  30  30  2017-12-22         @  GSW   L  106    113  40   ...      
..    ...  ..  ..         ...       ...  ...  ..  ...    ...  ..   ...      
52     56  53  53  2018-02-06       NaN  PHO   W  112     93  39   ...      
53     57  54  54  2018-02-08       NaN  OKC   W  106     81  42   ...      
54     58  55  55  2018-02-10         @  DAL   L  123    130  46   ...      
55     59  56  56  2018-02-14         @  NOP   L  117    139  46   ...      
56     60  57  57  2018-02-15         @  MIN   L  111    119  43   ...      
57     61  58  58  2018-02-23       NaN  DAL   W  124    102  48   ...      
58     62  59  59  2018-02-24         @  SAC   W  113    108  41   ...      
59     63  60  60  2018-02-26         @  ATL   W  123    104  47   ...      
60     66  61  61  2018-03-01         @  MIA   W  131    113  47   ...      
61     67  62  62  2018-03-03         @  SAS   W  116    112  40   ...      
62     68  63  63  2018-03-05       NaN  POR   L  103    108  34   ...      
63     69  64  64  2018-03-07       NaN  ORL   W  108    107  43   ...      
64     70  65  65  2018-03-09         @  DEN   L  116    125  45   ...      
65     71  66  66  2018-03-11       NaN  CLE   W  127    113  48   ...      
66     72  67  67  2018-03-13       NaN  DEN   W  112    103  40   ...      
67     73  68  68  2018-03-14         @  GSW   L  106    117  38   ...      
68     74  69  69  2018-03-16       NaN  MIA   L   91     92  32   ...      
69     75  70  70  2018-03-19         @  IND   L  100    110  38   ...      
70     76  71  71  2018-03-22         @  NOP   L  125    128  43   ...      
71     77  72  72  2018-03-24         @  MEM   W  100     93  35   ...      


In [53]:
opp_list=list(set(obj.game_log['2018']['Opp']))
obj.game_log['2018']['Opp']

0     PHO
1     IND
2     MIL
3     NOP
4     LAC
5     PHO
6     TOR
7     UTA
8     LAL
9     OKC
10    MEM
11    BRK
12    DEN
13    ORL
14    SAC
15    SAC
16    MEM
17    PHI
18    BRK
19    WAS
20    NYK
21    MIL
22    NOP
23    WAS
24    HOU
25    GSW
26    MIA
27    ORL
28    CHO
29    MIN
     ... 
43    CHI
44    TOR
45    BOS
46    DET
47    CHO
48    SAC
49    UTA
50    GSW
51    UTA
52    PHO
53    SAC
54    MIN
55    OKC
56    LAL
57    NYK
58    GSW
59    MIA
60    CLE
61    DET
62    LAC
63    HOU
64    BOS
65    OKC
66    NOP
67    LAC
68    MEM
69    DAL
70    SAS
71    DEN
72    UTA
Name: Opp, dtype: object

In [27]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
teamGameLogURL='https://www.basketball-reference.com/teams/CHO/2018/gamelog'
page = requests.get(teamGameLogURL)
soup = BeautifulSoup(page.content, 'html.parser') 
table = soup.find('div', class_="overthrow table_container", id="div_tgl_basic")
            
df = pd.read_html(table.prettify())[0]
df

Unnamed: 0 Unnamed: 1  Unnamed: 2  Team Unnamed: 4  Opponent   Rk    G  \
0           1          1  2017-10-18     @        DET         L   90  102   
1           2          2  2017-10-20   NaN        ATL         W  109   91   
2           3          3  2017-10-23     @        MIL         L   94  103   
3           4          4  2017-10-25   NaN        DEN         W  110   93   
4           5          5  2017-10-27   NaN        HOU         L   93  109   
5           6          6  2017-10-29   NaN        ORL         W  120  113   
6           7          7  2017-10-30     @        MEM         W  104   99   
7           8          8  2017-11-01   NaN        MIL         W  126  121   
8           9          9  2017-11-03     @        SAS         L  101  108   
9          10         10  2017-11-05     @        MIN         L   94  112   
10         11         11  2017-11-07     @        NYK         L  113  118   
11         12         12  2017-11-10     @        BOS         L   87   90   
12         13         13  2017-11-15   NaN        CLE         L  107  115   
13         14         14  2017-11-17     @        CHI         L  120  123   
14         15         15  2017-11-18   NaN        LAC         W  102   87   
15         16         16  2017-11-20   NaN        MIN         W  118  102   
16         17         17  2017-11-22   NaN        WAS         W  129  124   
17         18         18  2017-11-24     @        CLE         L   99  100   
18         19         19  2017-11-25   NaN        SAS         L   86  106   
19         20         20  2017-11-29     @        TOR         L  113  126   
20        NaN        NaN         NaN  Team        NaN  Opponent  NaN  NaN   
21         Rk          G        Date   NaN        Opp       W/L   Tm  Opp   
22         21         21  2017-12-01     @        MIA         L  100  105   
23         22         22  2017-12-04   NaN        ORL         W  104   94   
24         23         23  2017-12-06   NaN        GSW         L   87  101   
25         24         24  2017-12-08   NaN        CHI         L  111  119   
26         25         25  2017-12-09   NaN        LAL         L   99  110   
27         26         26  2017-12-11     @        OKC         W  116  103   
28         27         27  2017-12-13     @        HOU         L   96  108   
29         28         28  2017-12-15   NaN        MIA         L   98  104   
..        ...        ...         ...   ...        ...       ...  ...  ...   
60         57         57  2018-02-14     @        ORL         W  104  102   
61         58         58  2018-02-22   NaN        BRK         W  111   96   
62         59         59  2018-02-23     @        WAS         W  122  105   
63         60         60  2018-02-25   NaN        DET         W  114   98   
64        NaN        NaN         NaN  Team        NaN  Opponent  NaN  NaN   
65         Rk          G        Date   NaN        Opp       W/L   Tm  Opp   
66         61         61  2018-02-27   NaN        CHI         W  118  103   
67         62         62  2018-02-28     @        BOS         L  106  134   
68         63         63  2018-03-02     @        PHI         L   99  110   
69         64         64  2018-03-04     @        TOR         L   98  103   
70         65         65  2018-03-06   NaN        PHI         L  114  128   
71         66         66  2018-03-08   NaN        BRK         L  111  125   
72         67         67  2018-03-10   NaN        PHO         W  122  115   
73         68         68  2018-03-13     @        NOP         L  115  119   
74         69         69  2018-03-15     @        ATL         W  129  117   
75         70         70  2018-03-17     @        NYK         L  101  124   
76         71         71  2018-03-19     @        PHI         L   94  108   
77         72         72  2018-03-21     @        BRK         W  111  105   
78         73         73  2018-03-22   NaN        MEM         W  140   79   
79         74         74  2018-03-24     @        DAL         W  102   98   

In [55]:
from sklearn.preprocessing import OneHotEncoder as OHE
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer
ohe=OHE()
le=LabelEncoder()
lb=LabelBinarizer()
le_cols=le.fit_transform(obj.game_log['2018']['Opp'])
ohe_cols= ohe.fit_transform(le_cols)
lb_cols= lb.fit_transform(obj.game_log['2018']['Opp'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0

/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [90]:
from sklearn import base

class ColumnSelectTransformer(base.BaseEstimator, base.TransformerMixin):
    
    def __init__(self, col_names):
        self.col_names = col_names  # We will need these in transform()
    
    def fit(self, X, y=None):
        # This transformer doesn't need to learn anything about the data,
        # so it can just return self without any further processing
        return self
    
    def transform(self, X):
        # Return an array with the same number of rows as X and one
        # column for each in self.col_names


        return [[X.loc[i,self.col_names]] for i, v in X.iterrows()]


In [91]:
cst=ColumnSelectTransformer(['G','Away','daysRest','Opp'] )
cst.fit_transform(data, data['PTS'])

[[G             1
  Away          1
  daysRest     99
  Opp         PHO
  Name: 0, dtype: object], [G             2
  Away          1
  daysRest      2
  Opp         IND
  Name: 1, dtype: object], [G             3
  Away          1
  daysRest      1
  Opp         MIL
  Name: 2, dtype: object], [G             4
  Away          0
  daysRest      3
  Opp         NOP
  Name: 3, dtype: object], [G             5
  Away          0
  daysRest      2
  Opp         LAC
  Name: 4, dtype: object], [G             6
  Away          0
  daysRest      2
  Opp         PHO
  Name: 5, dtype: object], [G             7
  Away          0
  daysRest      2
  Opp         TOR
  Name: 6, dtype: object], [G             8
  Away          1
  daysRest      2
  Opp         UTA
  Name: 7, dtype: object], [G             9
  Away          0
  daysRest      1
  Opp         LAL
  Name: 8, dtype: object], [G            10
  Away          0
  daysRest      3
  Opp         OKC
  Name: 9, dtype: object], [G            11
  

In [62]:
features=['G','Away','daysRest']
data=obj.game_log['2018']
X=data[features].convert_objects(convert_numeric=True).values
X, lb_cols

/Users/terrykim/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  app.launch_new_instance()


(array([[  1.,   1.,  99.],
        [  2.,   1.,   2.],
        [  3.,   1.,   1.],
        [  4.,   0.,   3.],
        [  5.,   0.,   2.],
        [  6.,   0.,   2.],
        [  7.,   0.,   2.],
        [  8.,   1.,   2.],
        [  9.,   0.,   1.],
        [ 10.,   0.,   3.],
        [ 11.,   0.,   2.],
        [ 12.,   0.,   3.],
        [ 13.,   0.,   3.],
        [ 14.,   0.,   2.],
        [ 15.,   1.,   2.],
        [ 16.,   0.,   1.],
        [ 17.,   1.,   2.],
        [ 18.,   1.,   2.],
        [ 19.,   1.,   2.],
        [ 20.,   1.,   1.],
        [ 21.,   1.,   2.],
        [ 22.,   0.,   3.],
        [ 23.,   0.,   2.],
        [ 24.,   0.,   3.],
        [ 25.,   0.,   4.],
        [ 26.,   1.,   2.],
        [ 27.,   1.,   2.],
        [ 28.,   1.,   2.],
        [ 29.,   1.,   1.],
        [ 30.,   1.,   2.],
        [ 31.,   0.,   2.],
        [ 32.,   1.,  13.],
        [ 33.,   0.,   3.],
        [ 34.,   1.,   5.],
        [ 35.,   1.,   2.],
        [ 36.,   1.,

In [22]:
df=obj.game_log['2018']

In [25]:
cols=['OppPts','OppFG',
       u'OppFGA', u'Opp3P', u'Opp3PA',  u'OppFT',
       u'OppFTA', u'OppTRB', u'OppAST', u'OppSTL',
       u'OppBLK', u'OppTOV']
df[cols].astype('float').mean()

OppPts    99.841463
OppFG     37.280488
OppFGA    82.975610
Opp3P      9.487805
Opp3PA    25.987805
OppFT     15.792683
OppFTA    20.487805
OppTRB    41.609756
OppAST    19.951220
OppSTL     8.268293
OppBLK     4.634146
OppTOV    14.475610
dtype: float64

<bound method team_scraper.getTeamData of <__main__.team_scraper instance at 0x1107d4d40>>

In [15]:
obj.age

'27'

In [1]:
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn
from bokeh.transform import factor_cmap
from bokeh.io import show, output_notebook, curdoc
from bokeh.models import ColumnDataSource, Whisker, Callback, CustomJS
from bokeh.plotting import figure
import bokeh.layouts as layouts
import bokeh.models.widgets as widgets
output_notebook()

Loading BokehJS ...

In [1]:
%%bash 
jupyter notebook --version

5.4.1


In [10]:
import datetime as dt
bdate='1990-07-15'
str(int((dt.datetime.now()-dt.datetime.strptime(bdate,'%Y-%m-%d')).days/365.0))

'27'

In [12]:
run nba_stats.py

nba_stats.py:108: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
nba_stats.py:191: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  weight=soup.find("span", itemprop="weight")


6-3 195lb


nba_stats.py:232: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  RFG=RandomForestRegressor(min_samples_leaf=9)
nba_stats.py:233: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  RFG.fit(X,yi)


In [11]:
import nba_stats

teamURLdict = nba_stats.getTeamURLdict()

In [30]:
obj.game_log

{'2018':     index  Rk   G        Date     Age   Tm Unnamed: 5  Opp Unnamed: 7  GS  \
 0       0   1   1  2017-10-18  27-095  POR          @  PHO    W (+48)   1   
 1       1   2   2  2017-10-20  27-097  POR          @  IND    W (+18)   1   
 2       2   3   3  2017-10-21  27-098  POR          @  MIL     L (-3)   1   
 3       3   4   4  2017-10-24  27-101  POR        NaN  NOP    W (+10)   1   
 4       4   5   5  2017-10-26  27-103  POR        NaN  LAC     L (-1)   1   
 5       5   6   6  2017-10-28  27-105  POR        NaN  PHO     W (+7)   1   
 6       6   7   7  2017-10-30  27-107  POR        NaN  TOR    L (-14)   1   
 7       7   8   8  2017-11-01  27-109  POR          @  UTA     L (-9)   1   
 8       8   9   9  2017-11-02  27-110  POR        NaN  LAL     W (+3)   1   
 9       9  10  10  2017-11-05  27-113  POR        NaN  OKC     W (+4)   1   
 10     10  11  11  2017-11-07  27-115  POR        NaN  MEM     L (-1)   1   
 11     11  12  12  2017-11-10  27-118  POR        NaN  

In [19]:
teamURLdict['Atlanta Hawks']

'/teams/ATL/'

In [25]:
[k for k, v in teamURLdict.iteritems() if obj.team in v][0]

'Portland Trail Blazers'

In [31]:
#results.index.name='Category'
#results=results.reset_index()

data = dict(results[results.columns])
source=ColumnDataSource(data)

columns = [TableColumn(field=col, title=col) for col in results.columns]

data_table = DataTable(source=source,columns=columns,width=400, height=280,editable=True)
data_table.row_headers = False


source.callback = CustomJS(args=dict(source=source), code="""
       console.log( '#Selected rows:');
       var indices = source.selected["1d"].indices;
       for (var i = 0; i<indices.length; i++){
           console.log(i+":"+indices[i]);
       }
       """)

def table_select_callback(attr, old, new):
    selected_cat = new['1d']['indices'][0]
    RFG=obj.models['2018']['RFG'][selected_cat]
    
    features=['Game Number','Home/Away','Days Rest']
    groups= features
    counts = RFG.feature_importances_

    chart_data = ColumnDataSource(data=dict(groups=groups, counts=counts))

    p = figure(x_range=groups, plot_height=350, toolbar_location=None, title="Feature Importance - "+cat, y_range=(0,1.1))
    p.vbar(x='groups', top='counts', width=0.9, source=chart_data, 
           line_color='white', fill_color=factor_cmap('groups', palette=["#962980","#295f96","#29966c"],
                                                      factors=groups))

    p.xgrid.grid_line_color = None
    
    root_layout.children[1] = p


def create_featureimp_plot(obj, cat='PTS'):

    
    features=['Game Number','Home/Away','Days Rest']
    groups= features
    RFG=obj.models['2018']['RFG'][cat]
    counts =  RFG.feature_importances_

    chart_data = ColumnDataSource(data=dict(groups=groups, counts=counts))

    p = figure(x_range=groups, plot_height=350, toolbar_location=None, title="Feature Importance - "+cat, y_range=(0,1.1))
    p.vbar(x='groups', top='counts', width=0.9, source=chart_data, 
           line_color='white', fill_color=factor_cmap('groups', palette=["#962980","#295f96","#29966c"],
                                                      factors=groups))

    p.xgrid.grid_line_color = None
    
    return p   

source.on_change('selected', table_select_callback)

feature_imp_plot = create_featureimp_plot(obj)

root_layout = layouts.Column(data_table, widgets.Div(text='Select Category'))
curdoc().add_root(root_layout)
layout=layouts.row(data_table,feature_imp_plot)
show(layout)



{}

In [6]:
show(data_table)

In [7]:


def table_select_callback(attr, old, new):
    selected_cat = new['1d']['indices'][0]
    RFG=obj.models['2018']['RFG'][selected_cat]
    

    features=['Game Number','Home/Away','Days Rest']
    groups= features
    counts = RFG.feature_importances_


    source = ColumnDataSource(data=dict(groups=groups, counts=counts))

    p = figure(x_range=groups, plot_height=350, toolbar_location=None, title="Feature Importance - "+cat, y_range=(0,1.1))
    p.vbar(x='groups', top='counts', width=0.9, source=source, 
           line_color='white', fill_color=factor_cmap('groups', palette=["#962980","#295f96","#29966c"],
                                                      factors=groups))

    p.xgrid.grid_line_color = None
    
    root_layout.children[1] = p


source.on_change('selected', table_select_callback)

root_layout = layouts.Column(data_table, widgets.Div(text='Select Category'))
curdoc().add_root(root_layout)
show(vform(data_table))

In [32]:
import numpy as np
cat='3P'
RFG=obj.models['2018']['RFG'][cat]

features=['Game Number','Home/Away','Days Rest']
groups= features
counts = RFG.feature_importances_


source = ColumnDataSource(data=dict(groups=groups, counts=counts))

p = figure(x_range=groups, plot_height=350, toolbar_location=None, title="Feature Importance - "+cat, y_range=(0,1.1))
p.vbar(x='groups', top='counts', width=0.9, source=source, 
       line_color='white', fill_color=factor_cmap('groups', palette=["#962980","#295f96","#29966c"],
                                                  factors=groups))

p.xgrid.grid_line_color = None


show(p)


In [4]:
print results['Actual'].astype('float').map(lambda x: '{:.0f}'.format(x))

FG      13
FGA     25
FG%     52
3P       4
3PA     10
FT       6
FTA      6
FT%    100
TRB      1
AST     10
STL      1
BLK      0
TOV      0
PTS     36
Name: Actual, dtype: object


In [16]:
results=results.convert_objects(convert_numeric='True')
results.apply(lambda x: ['{:.1f}'.format(x) if v<=1 else '{:.0f}'.format(x) for i,v in enumerate(x)] ,axis=0)


/Users/terrykim/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  if __name__ == '__main__':


ValueError: ("Unknown format code 'f' for object of type 'str'", u'occurred at index Season Average')

In [12]:
results.dtypes

Season Average    float64
Predictions       float64
Actual            float64
dtype: object

In [3]:
results

NameError: name 'results' is not defined

In [11]:
results['Actual']=results['Actual'].astype('float')
results.loc['FG%','Actual']=results.loc['FG','Actual']/results.loc['FGA','Actual']
results

Season Average       Predictions  Actual
FG    [8.50684931507]   [8.74561796537]   13.00
FGA   [19.3835616438]   [20.6777529642]   25.00
3P     [3.1095890411]   [2.82772788615]    4.00
3PA   [8.61643835616]   [9.91161596857]   10.00
FT    [6.75342465753]   [8.58561437413]    6.00
FTA    [7.3698630137]   [9.56954483054]    6.00
TRB   [4.45205479452]   [4.20899068157]    1.00
AST   [6.58904109589]   [5.75093465942]   10.00
STL   [1.05479452055]   [1.48501194458]    1.00
BLK  [0.369863013699]  [0.342403846154]    0.00
TOV   [2.82191780822]   [1.63778149387]    0.00
PTS   [26.8767123288]   [31.2169996549]   36.00
FG%               NaN               NaN    0.52

In [21]:
import datetime as dt
date='4/11/18'
formatted_date=dt.datetime.strptime(date, '%m/%d/%y').strftime('%Y-%m-%d')

cats = ['FG','FGA','3P','3PA','FT','FTA','TRB','AST','STL','BLK','TOV','PTS']
data=obj.game_log['2018']
data[cats][data['Date']==formatted_date].squeeze() 

FG     13
FGA    25
3P      4
3PA    10
FT      6
FTA     6
TRB     1
AST    10
STL     1
BLK     0
TOV     0
PTS    36
Name: 72, dtype: object

In [31]:
features=['G','Away','daysRest']
feature_inputs=data[features][data['Date']==formatted_date].values

In [4]:
obj.models['2018']['dummyReg']['3P'].predict([4,1,0])

/Users/terrykim/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 3.10958904])

## Set labels (y)

In [33]:
import pandas as pd
cats = ['FG','FGA','3P','3PA','FT','FTA','TRB','AST','STL','BLK','TOV','PTS']
y=data[cats].convert_objects(convert_numeric=True) # must convert values to numeric, current dtype was object

/Users/terrykim/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  app.launch_new_instance()


## Set features (X)

In [34]:
features=['G','Away','daysRest']
X=data[features].convert_objects(convert_numeric=True)

/Users/terrykim/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  from ipykernel import kernelapp as app


## Apply Linear 

### Assess baseline error i.e. all predictions are season averages (mean of data set)

In [35]:
from sklearn.dummy import DummyRegressor
dummyreg=DummyRegressor(strategy='mean')
dummyreg.fit(X,y)


DummyRegressor(constant=None, quantile=None, strategy='mean')

In [36]:
dummyreg.predict(feature_inputs)

array([[  8.50684932,  19.38356164,   3.10958904,   8.61643836,
          6.75342466,   7.36986301,   4.45205479,   6.5890411 ,
          1.05479452,   0.36986301,   2.82191781,  26.87671233]])

In [ ]:
for cat in cats:
    yi=y[cat]
    dummyreg=DummyRegressor(strategy='mean')
    dummyreg.fit(X,yi)
    print cat
    print compute_error(dummyreg, X, yi)
    print '\n'


In [ ]:
import numpy as np
from sklearn.base import BaseEstimator, RegressorMixin, TransformerMixin
from sklearn import neighbors
from sklearn import ensemble
from sklearn import linear_model
from sklearn.pipeline import Pipeline, FeatureUnion

class EnsembleTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, base_estimator, residual_estimators):
        self.base_estimator = base_estimator
        self.residual_estimators = residual_estimators
    
    def fit(self, X, y):
        self.base_estimator.fit(X, y)
        y_err = y - self.base_estimator.predict(X)
        for est in self.residual_estimators:
            est.fit(X, y_err)
        return self
    
    def transform(self, X):
        all_ests = [self.base_estimator] + list(self.residual_estimators)
        return np.array([est.predict(X) for est in all_ests]).T


In [ ]:
from sklearn import model_selection
from scipy import stats

cv = model_selection.ShuffleSplit(n_splits=20, test_size=0.2, random_state=42)
def compute_error(est, X, y):
    return -model_selection.cross_val_score(est, X, y, cv=cv, scoring='neg_mean_squared_error').mean()

def abs_corr(x, y):
    return np.abs(stats.pearsonr(x, y)[0])


In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
ensemble_pipe = Pipeline([
        ('ensemble', EnsembleTransformer(
                Ridge(),
                 ensemble.RandomForestRegressor(min_samples_leaf=20))),
        ('blend', Ridge())
    ])
ensemble_pipe.fit(X, y)


### Try different linear regression models: standard, ridge, lasso

In [ ]:
linreg=linear_model.LinearRegression()
linreg.fit(X,y)
compute_error(linreg, X, y)
linreg.coef_

In [ ]:
ridge=Ridge()
ridge.fit(X,y)
compute_error(ridge, X, y)

In [ ]:
lasso=linear_model.Lasso()
lasso.fit(X,y)
compute_error(lasso, X, y)

In [ ]:
lasso.coef_

In [ ]:
y_predict=linreg.predict([40,0,0])
pd.Series(index=cats,data=y_predict[0])

In [ ]:
compute_error(linreg, X, y)

In [ ]:
ensemble_pipe.predict([70,0,0])

In [ ]:
from sklearn.ensemble import RandomForestRegressor


RFG=RandomForestRegressor(min_samples_leaf=9)
RFG.fit(X,y)
compute_error(RFG, X, y)

In [ ]:
from sklearn.model_selection import GridSearchCV
param_dict={'min_samples_leaf': [i for i in xrange(9,11)]}

grid = GridSearchCV(RFG,param_dict)
grid.fit(X, y['FGA'])
compute_error(grid, X, y['FGA'])

In [ ]:
grid.best_params_

In [ ]:
RFG.feature_importances_

In [ ]:
RFG.n_features_

In [ ]:
for cat in cats:
    yi=y[cat]

    print cat

    dummyreg=DummyRegressor(strategy='mean')
    dummyreg.fit(X,yi)

    print 'Dummy Regressor Error: {}'.format(compute_error(dummyreg, X, yi))
    
    RFG=RandomForestRegressor(min_samples_leaf=9)
    RFG.fit(X,yi)
    
    print 'Random Forest Regressor Error: {}'.format(compute_error(RFG, X, yi))
    print RFG.feature_importances_
    print '\n'

In [ ]:
np.std([tree.feature_importances_ for tree in RFG.estimators_],axis=0)

In [8]:
import datetime
now = datetime.datetime.now()
date=datetime.datetime.strptime('4/11/18','%m/%d/%y')

In [10]:
date<now

True